"""Generate a markdown summary of all E1 results in e1/results/.

Idempotent; re-run any time to refresh the report from whatever JSONs exist.
Keys results by (model, steps, topk, temperature).
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(HERE, "results")
OUT = os.path.join(HERE, "REPORT.md")

MODELS = ["sfm", "sfm-dit", "flm", "duo", "mdlm"]
MODEL_LABEL = {
    "sfm": "S-FLM (sphere-arch)",
    "sfm-dit": "S-FLM (sphere-DiT)",
    "flm": "FLM (Euclidean flow)",
    "duo": "Duo (uniform diff.)",
    "mdlm": "MDLM (masked diff.)",
}
STEPS = [4, 8, 16, 32]


def load(path):
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return None


def collect(prefix):
    data = {}
    for fn in sorted(os.listdir(RESULTS)):
        if not fn.startswith(prefix) or not fn.endswith(".json"):
            continue
        r = load(os.path.join(RESULTS, fn))
        if r is None:
            continue
        key = (r["model"], r["steps"], r.get("topk"), r.get("temperature"))
        data[key] = r
    return data


def fmt_acc(r):
    return f"{r['accuracy']*100:.1f}%" if r else "—"


def fmt_fr(r):
    if not r:
        return "—"
    fr = r["overall_firing_rate"].get("1")
    return f"{fr:.4f}" if fr is not None else "—"


def table(lines, title, models, keyfn, valfn):
    lines.append(f"### {title}\n")
    lines.append("| model | " + " | ".join(f"s={s}" for s in STEPS) + " |")
    lines.append("|---" * (len(STEPS) + 1) + "|")
    for m in models:
        row = [MODEL_LABEL[m]]
        for s in STEPS:
            row.append(valfn(keyfn(m, s)))
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")


def main():
    sigma = collect("sigma_")
    qual = collect("quality_")
    temps = sorted({k[3] for k in sigma} | {k[3] for k in qual},
                   key=lambda t: (t is None, t or 0))

    lines = ["# E1 results: sigma-delta sparsity of flow vs masked language models\n",
             "_Generated by `summarize.py` from `e1/results/*.json`._\n"]

    for T in temps:
        tlabel = "T=1.0 (default)" if T is None else f"T={T}"
        lines.append(f"## Temperature: {tlabel}\n")

        lines.append("#### GSM8K accuracy vs NFE (full 1320)\n")
        def qkey(m, s):
            return qual.get((m, s, None, T))
        table(lines, "", MODELS, qkey, fmt_acc)

        lines.append("#### Sigma-delta firing rate (K=1) vs NFE (lower = sparser)\n")
        def skey(m, s):
            return sigma.get((m, s, None, T))
        table(lines, "", MODELS, skey, fmt_fr)

        lines.append("#### Raw activation-change magnitude (mean |Δv|)\n")
        def dkey(m, s):
            r = sigma.get((m, s, None, T))
            return f"{r['overall_raw_delta']:.5f}" if r else "—"
        lines.append("| model | " + " | ".join(f"s={s}" for s in STEPS) + " |")
        lines.append("|---" * (len(STEPS) + 1) + "|")
        for m in MODELS:
            row = [MODEL_LABEL[m]]
            for s in STEPS:
                row.append(dkey(m, s))
            lines.append("| " + " | ".join(row) + " |")
        lines.append("")

        lines.append("#### Architecture-controlled (same DDiTBlock): flow vs masked\n")
        for s in STEPS:
            a = fmt_fr(sigma.get(("sfm-dit", s, None, T)))
            b = fmt_fr(sigma.get(("mdlm", s, None, T)))
            c = fmt_fr(sigma.get(("flm", s, None, T)))
            qa = fmt_acc(qual.get(("sfm-dit", s, None, T)))
            qb = fmt_acc(qual.get(("mdlm", s, None, T)))
            qc = fmt_acc(qual.get(("flm", s, None, T)))
            lines.append(f"- s={s}: sfm-dit acc={qa} fr={a} | "
                         f"flm acc={qc} fr={c} | mdlm acc={qb} fr={b}")
        lines.append("")

        lines.append("#### Per-step firing trajectory (s=16)\n")
        for m in MODELS:
            r = sigma.get((m, 16, None, T))
            if r and r["per_step_firing_rate"]:
                traj = ", ".join(f"{v:.3f}" for v in r["per_step_firing_rate"])
                lines.append(f"- **{MODEL_LABEL[m]}**: [{traj}]")
        lines.append("")

    lines.append("## Notes / caveats\n")
    lines.append("- All runs on Apple MPS (float32, `use_float64=false`, `slerp_precision=float32`).\n")
    lines.append("- **T=1.0 with default decoders is not a meaningful quality regime**: "
                 "masked/uniform (MDLM/Duo) ancestral sampling at T=1 is too stochastic "
                 "(gibberish), and S-FLM exact-velocity plateaus at ~12% per the paper. "
                 "The T=0.1 sweep is the meaningful quality comparison (matches the paper's Fig. 3).\n")
    lines.append("- Sigma-delta threshold `tau = mean|v_0|/K` per layer (N-MDLM adaptive step); "
                 "K=1 is the headline aggressive-sparsity number.\n")
    lines.append("- Top-1 velocity (WTA) readout variants are stored separately; see "
                 "`quality_*_topk1_*.json`.\n")

    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
